apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: destinations.rudder.io
spec:
  group: rudder.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Cluster
  names:
    plural: destinations
    singular: destination
    kind: Destination
    shortNames:
    - dest
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            ipRange:
              type: string
            port:
              type: integer
