apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: routes.rudder.io
spec:
  group: rudder.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Cluster
  names:
    plural: routes
    singular: routes
    kind: Route
    shortNames:
    - rt
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            dest:
              type: string
            selector:
              type: object