apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sources.rudder.io
spec:
  group: rudder.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Cluster
  names:
    plural: sources
    singular: source
    kind: Source
    shortNames:
    - src
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            ipRange:
              type: string
            port:
              type: integer
