kind: Service
apiVersion: v1
metadata:
  name: proxy-1
  labels:
    app: proxy
spec:
  selector:
    app: proxy
  ports:
  - name: git
    protocol: TCP
    port: 2222
    targetPort: 80
  - name: bastion 
    protocol: TCP
    port: 2424
    targetPort: 80
  - name: admin
    protocol: TCP
    port: 3636
    targetPort: 80
  type: LoadBalancer
  #  externalTrafficPolicy: Local
