apiVersion: v1
kind: Pod
metadata:
  name: rudder
  labels:
    app: rudder
spec:
  serviceAccount: rudder-viewer
  hostNetwork: true
  terminationGracePeriodSeconds: 0
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - topologyKey: "kubernetes.io/hostname"
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - nginx
  containers:
    - name: rudder
      image: asia.gcr.io/robust-charge-241703/katsew/rudder:dev
      imagePullPolicy: Always
      command:
        - tail
        - -f
        - /dev/null
      ports:
        - containerPort: 80
      securityContext:
        privileged: true
        runAsUser: 0
        runAsGroup: 0
        capabilities:
          add:
            - NET_ADMIN
            - NET_RAW
