kind: Service
apiVersion: v1
metadata:
  name: nginx-2
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 18080
    targetPort: 80
  type: LoadBalancer
  externalTrafficPolicy: Local
