kind: Service
apiVersion: v1
metadata:
  name: nginx-5
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
  - name: nginx
    protocol: TCP
    port: 17070
    targetPort: 80
  type: NodePort
