apiVersion: v1
kind: Pod
metadata:
  name: rudder-debug
  labels:
    app: debugger
spec:
  serviceAccount: rudder-viewer
  hostNetwork: true
  terminationGracePeriodSeconds: 0
  containers:
    - name: rudder
      image: rudder:dev
      imagePullPolicy: IfNotPresent
      command:
        - tail
        - -f
        - /dev/null
      ports:
        - containerPort: 80
      securityContext:
        privileged: true
        capabilities:
          add:
            - NET_ADMIN
            - NET_RAW
      volumeMounts:
        - name: bin
          mountPath: /usr/local/bin
  volumes:
    - name: bin
      hostPath:
        path: /go/bin
        type: Directory
