kind: Service
apiVersion: v1
metadata:
  name: debug-svc
  labels:
    app: debugger
spec:
  selector:
    app: debugger
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
  type: LoadBalancer
  externalTrafficPolicy: Local